import 'package:flutter/material.dart';

List<Map<String, dynamic>> baseCampRouteData = [
  {
    "Route": "Route 1",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 1,
    "Top Weight": 10 * 1,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 2",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 2,
    "Top Weight": 10 * 2,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 3",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 3,
    "Top Weight": 10 * 3,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 4",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 4,
    "Top Weight": 10 * 4,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 5",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 5,
    "Top Weight": 10 * 5,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 6",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 6,
    "Top Weight": 10 * 6,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 7",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 7,
    "Top Weight": 10 * 7,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 8",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 8,
    "Top Weight": 10 * 8,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 9",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 9,
    "Top Weight": 10 * 9,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 10",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 10,
    "Top Weight": 10 * 10,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 11",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 11,
    "Top Weight": 10 * 11,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 12",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 12,
    "Top Weight": 10 * 12,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 13",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 13,
    "Top Weight": 10 * 13,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 14",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 14,
    "Top Weight": 10 * 14,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 15",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 15,
    "Top Weight": 10 * 15,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 16",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 16,
    "Top Weight": 10 * 16,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 17",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 17,
    "Top Weight": 10 * 17,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 18",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 18,
    "Top Weight": 10 * 18,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 19",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 19,
    "Top Weight": 10 * 19,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
  {
    "Route": "Route 20",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 20,
    "Top Weight": 10 * 20,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
  },
];
List<Map<String, dynamic>> crestRouteData = [
  {
    "Route": "Route 1",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 1,
    "Top Weight": 10 * 1,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
  {
    "Route": "Route 2",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 2,
    "Top Weight": 10 * 2,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
  {
    "Route": "Route 3",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 3,
    "Top Weight": 10 * 3,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
  {
    "Route": "Route 4",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 4,
    "Top Weight": 10 * 4,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
  {
    "Route": "Route 5",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 5,
    "Top Weight": 10 * 5,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
  {
    "Route": "Route 6",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 6,
    "Top Weight": 10 * 6,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
  {
    "Route": "Route 7",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 7,
    "Top Weight": 10 * 7,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
  {
    "Route": "Route 8",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 8,
    "Top Weight": 10 * 8,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
  {
    "Route": "Route 9",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 9,
    "Top Weight": 10 * 9,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
  {
    "Route": "Route 10",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 10,
    "Top Weight": 10 * 10,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
  {
    "Route": "Route 11",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 11,
    "Top Weight": 10 * 11,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
  {
    "Route": "Route 12",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 12,
    "Top Weight": 10 * 12,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
  {
    "Route": "Route 13",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 13,
    "Top Weight": 10 * 13,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
  {
    "Route": "Route 14",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 14,
    "Top Weight": 10 * 14,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
  {
    "Route": "Route 15",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 15,
    "Top Weight": 10 * 15,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
  {
    "Route": "Route 16",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 16,
    "Top Weight": 10 * 16,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "isTop10": false,
    "Verified": false,
    "Verified By": "",
  },
];
